# Generated by Django 3.0.4 on 2020-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp1', '0003_auto_20200330_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
